### ISSUE TITLE
wm_debug times requests out

### ISSUE THREAD

**Issue by yrashk** [awetzel/ewebmachine#11] opened 2015-01-26 05:06 UTC
I have a reproducible case when (especially after the first *slowly processed* request), the follow up requests fail and after a while I see this printed:

```
** (exit) exited in: GenServer.call(Ewebmachine.Log, {:update, #Function<3.54786035/1 in Ewebmachine.Log.put/1>}, 5000)
    ** (EXIT) time out
```

Thoughts?

This seem to happen regardless where there's an active EventStream and the only mediation found so far is disabling wm_debug completely.

**Comment by awetzel** [comment] 2015-01-26 06:24
Yes I saw that happened too, I think this is only due to the linear lookup of the key, the thing is :

-  the search do not have to lock the log server... only doing that because of the "Agent", I can put that into a genserver and use a GenServer.reply
- we can use a gb_tree
- we can use a "ets" `ordered_set`

I will see if I can make the adjustment quickly

**Comment by yrashk** [comment] 2015-01-26 07:08
That would be sweet!

**Comment by awetzel** [comment] 2015-01-26 07:47
That s it I have just released and push v2.0.5 containing all your remarks and more additions. I also added a Changelog file.

**Comment by yrashk** [comment] 2015-01-26 07:48
Wow, going to upgrade in as second!

On Mon, Jan 26, 2015 at 2:47 PM, Arnaud Wetzel <notifications@github.com>
wrote:

> That s it I have just released and push v2.0.5 containing all your remarks
> and more additions. I also added a Changelog file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awetzel/ewebmachine/issues/11#issuecomment-71423919>.
>



-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by awetzel** [comment] 2015-01-26 08:06
Please tell me if you see the bug again and if the fixes are ok for you, I am going to sleep, see you. Thank you very much again :)

**Comment by yrashk** [comment] 2015-01-26 08:10
The error is gone, but when wm_debug is enabled, the requests go through very slowly (1-2 seconds). Disabling wm_debug immediately resolves the issue.

**Comment by awetzel** [comment] 2015-01-26 15:38
When I used webmachine (from basho) the debug logging became unusable when body produced was big, because for each handler call, the entire input conn/state and output conn/state are copied in the log. Maybe this is also the case with my inmemory implementation in ewebmachine and the solution could be to simply slice the resp_body in the log when it is too big ?

Actually I cannot do anything because I cannot reproduce it... you can maybe do a

```elixir
log = `Ewebmachine.Log.get("log_id_of_the_slow_query") |> :erlang.term_to_binary`
File.write!("yourlog",log)
```

And send me the file so I can reproduce myself the problem ?

**Comment by yrashk** [comment] 2015-01-26 15:41
Actually, I can't reproduce it now, either. I'll keep an eye, though!

On Mon, Jan 26, 2015 at 10:38 PM, Arnaud Wetzel <notifications@github.com>
wrote:

> When I used webmachine (from basho) the debug logging became unusable when
> body produced was big, because for each handler call, the entire input
> conn/state and output conn/state are copied in the log. Maybe this is also
> the case with my inmemory implementation in ewebmachine and the solution
> could be to simply slice the resp_body in the log when it is too big ?
>
> Actually I cannot do anything because I cannot reproduce it... you can
> maybe do a
>
> log = `Ewebmachine.Log.get("log_id_of_the_slow_query") |> :erlang.term_to_binary`File.write!("yourlog",log)
>
> And send me the file so I can reproduce myself the problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awetzel/ewebmachine/issues/11#issuecomment-71479628>.
>



-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by awetzel** [comment] 2015-09-11 03:27
I have not seen the issue since january, so I assume it s ok now, thank again I close the issue

**Closed by awetzel** 2015-09-11 03:27 UTC
